version: "3.8"

services:
  backend:
    container_name: auth-backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    environment:
      - DATABASE_URL=${DATABASE_URL}
    command: sh -c "npx prisma generate && node main.js"
